guild: 337666388527153163

server_browser:
    channel: 824520391947059210
    query_interval: 20
    servers:
        - name: 'Official Server #1'
          address: '104.243.41.183'
          query_port: 7758
        - name: 'Official Server #2'
          address: '104.243.41.183'
          query_port: 7778
        - name: 'Official Armored Server #1'
          address: '104.243.41.183'
          query_port: 7798
        - name: 'Official Beta Server'
          address: '104.243.41.183'
          query_port: 7818

event_roster:
    axis_role: 1052851730796249088
    allied_role: 1052851743135891456
    sl_role: 1052852476849692706