version: "3.3"

services:
  bot:
    container_name: daklight-discord-bot
    image: daklight-discord-bot
    build:
      context: .
      dockerfile: Dockerfile.prod
    secrets:
      - token

secrets:
  token:
    file: secrets/token
